-- CreateTable
CREATE TABLE `task` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `taskName` VARCHAR(191) NOT NULL,
    `taskCreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `author` VARCHAR(191) NULL,
    `doDateTask` DATETIME(3) NULL,
    `updateTaskTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `deleteTaskTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `taskDescription` VARCHAR(191) NULL,
    `deleteFlag` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
